if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    print("Using Clang")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler/clang.cmake)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    print("Using GCC")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler/gcc.cmake)
else()
    fatal_error("Compiler '${CMAKE_CXX_COMPILER_ID}' is not supported")
endif()
